@startuml

title Механизм работы технологий crossfire.js

participant script as js
participant "crossfire.js" as cf
participant WebEngine as web
participant "VirtualMachineStack (QML)" as qvms
participant "VirtualMachineStack (C++)" as cvms

' unclosed statements
activate cvms #lightgrey
activate qvms #lightgrey
activate web

activate js 
	js -[#blue]> cf: icL.crossfire(...)
	activate cf
		cf -> cf: получения\n идентификатора
		cf -> cf: регистрация\n функций\n обратной связи
		cf -[#green]-> web: console.log(...)
		cf -[#red]> js: возврат
	deactivate cf
deactivate js	
web -> web: запуск\n обработчика\n сигнала
activate web #springgreen
	web -[#blue]> cvms: runFunction(...)
	activate cvms #springgreen
		cvms -> cvms: создание\n прерываний icL
		cvms -[#red]> web: возврат
	deactivate cvms
deactivate web

cvms -> cvms: выполнения кода
cvms -> cvms: выполнения\n функций onStop
activate cvms #lightgrey
	cvms -[#green]-> qvms: requestJsCodeExecution
	activate qvms #limegreen
		qvms -[#blue]> web: runJavaScript
		activate web #limegreen
			web -[#green]-> cf: запрос на\n выполнение\n функций\n обратной\n связи
			web -[#red]> qvms: возврат
		deactivate web
	deactivate qvms
deactivate cvms

cf -> cf: обработка запроса
activate cf
	cf -[#blue]> js: вызов\n функций\n обратной\n связи
	activate js
		js -> js: выполнение
		js -[#red]> cf: возврат
	deactivate js
deactivate cf

!include uml_style.iuml

@enduml