@startuml

title Server.onRequestExecuteJS()

start

:webEngine.runJavaScript(code, lambda)|
note right
	При завершений будет
	выпольнена функция
	lambda
end note

!include uml_style.iuml
stop

@enduml