@startuml

!include uml_style.iuml

actor Пользователь as юзер

rectangle "Инициализация" {
	юзер -> (Открывает программу)
	юзер -> (Создаёт или открывает файл)
	(Открывает программу) -[hidden]- (Создаёт или открывает файл)
}

rectangle "Работа" {
	юзер -> (Пишет код)
	юзер -> (Запускает интерпретор)
	(Пишет код) -[hidden]- (Запускает интерпретор)
	юзер -> (Посмотрит результаты выпольнения)
	(Запускает интерпретор) -[hidden]- (Посмотрит результаты выпольнения)
	юзер -> (Исправляет код)
	(Посмотрит результаты выпольнения) -[hidden]- (Исправляет код)
	юзер -> (Повторно запскает интерпретатор)
	(Исправляет код) -[hidden]- (Повторно запскает интерпретатор)
}

@enduml