@startuml

!include uml_style.iuml

actor Пользователь as юзер

rectangle "Инициализация" {
	юзер -> (Открывает программу)
	юзер -> (Создаёт или открывает файл)
	(Открывает программу) -[hidden]- (Создаёт или открывает файл)
}

rectangle "Работа" {
	юзер -> (Пишет код)
	юзер -> (Запускает интерпретатор)
	(Пишет код) -[hidden]- (Запускает интерпретатор)
	юзер -> (Посмотрит результаты выполнения)
	(Запускает интерпретор) -[hidden]- (Посмотрит результаты выполнения)
	юзер -> (Исправляет код)
	(Посмотрит результаты выполнения) -[hidden]- (Исправляет код)
	юзер -> (Повторно запускает интерпретатор)
	(Исправляет код) -[hidden]- (Повторно запускает интерпретатор)
}

@enduml