@startuml

title DataState.getType()

start

:ret = NODATA;
:type = dataMap[name].type()|

if (type = Bool?) then (Да)
	-[#blue]->
	:ret = BOOL;
else if (type = Int?) then (Да)
	-[#blue]->
	:ret = INT;
else if (type = Double?) then (Да)
	-[#blue]->
	:ret = DOUBLE;
else if (type = String?) then (Да)
	-[#blue]->
	:ret = STRING;
else if (type = StringList?) then (Да)
	-[#blue]->
	:ret = List;
else if (type = CostumType?) then (Да)
	-[#blue]->
	:ret = ELEMENT;
else (Нет)
	-[#red]->
endif

:return ret;

stop


!include uml_style.iuml
@enduml