@startuml

!include uml_style.iuml
title Диаграмма классов

DataState <|-left- StackState
DataState <|-right- MemoryState
DataState -up-* WebElement
StackStateIt *-- StackState
MemoryStateIt *-- MemoryState
Memory *-- StackStateIt
Memory *-- FunctionContainer
Memory *-- MemoryStateIt

StackStateIt -right[hidden]- FunctionContainer

class Memory {
	StackStateIt stackIt
	MemoryStateIt stateIt
	FunctionContainer functions
}

@enduml