@startuml

title StackStateIt.getContainer(name)

start

:ret = nullptr;
:it = m_stack;
while (ret == nullptr && it != nullptr?)
	-[#blue]-> Да;
	if (it.contains(name)) then (Да)
		-[#blue]->
		:ret = it;
	else (Нет)
		-[#red]->
		:it = it.getPrev();
	endif
	-[#orange]->
endwhile (Нет)

:return ret == nullptr ? m_stack : ret;

stop


!include uml_style.iuml
@enduml