!include uml_style.iuml
title Handler.checkPrev
skinparam defaultTextAlignment left

start

:found = false;
:context = prev;

while (context != nullptr) 
	if (context.role == Try)
		:found = true;
		:break;
	endif
endwhile

:return found;

stop
@enduml