!include uml_style.iuml
title Object.containsData
start
:result = true;
if (dataType == Void || ((container == nullptr || name.isEmpty()) && value.isNull())) then (Да)
	-[#blue]->	
	:result = false;
else
	-[#red]->
endif
stop
@enduml