@startuml

!include uml_style.iuml
title Поиск грани команды

start

:получение следующего символа|

if (это {?) then (Да)
	-[#blue]->
	:левая грань = текущая позиция + 1;
	:поиск конца блока команд;
	if (текущий символ }?) then (Да)
		-[#blue]->
		:синтаксическая\n ошибка>
	else (Нет)
		-[#red]->
		:правая грань =\n текущая позиция;
	endif
else (Нет)
	-[#red]->
	:поиск один из символов окончания команды|
	if (найдено;?) then (Да)
		-[#blue]->
		:правая грань = текущая позиция;
		:ВиртиальнаяМашина\n.commandProcessing = false;
	else (Нет)
		-[#red]->
		:синтаксическая ошибка>
	endif
endif

stop

@enduml