@startuml

!include uml_style.iuml
title Парсинг логических выражений

start

:создания массива сохранений данных об операторов;

while (конец строки?)
	-[#blue]-> Да;
	:поиск оператора|
	:добавления данный о нём в массиве;
	-[#orange]->
endwhile (Нет)

:поиск максимума;
:разделение выражений на части;
:рекурсивный вызов данной функций для каждой часть|

stop

@enduml