@startuml

!include uml_style.iuml
title Парсинг аргумента
start

:Получения типа данных;
:Получения текущего или следующего символа;

if (Тип зарегистрирован?) then (Да)
	-[#blue]->
	if (текущий символ >?) then (Да)
		-[#blue]->
		:получения имени перемены|
		:создание контекста;
	else (Нет)
		-[#red]->
		:синтаксическая ошибка: неожиданный символ>
	endif
else (Нет)
	-[#red]->
	:синтаксическая ошибка: неизвестный тип данных>
endif

stop
@enduml