@startuml

!include wb_style.iuml

start
:<void>;

if (-i || ignore)
	:set up ignore tag;
	:read next keyword;
endif;

if (-o || optional)
	:set up optional tag;
	:read next keyword;
endif;

if (if)
	
else if (on)

else if (read)
	
else if (new)
	
else if (tab)
	
else if (wait)
	
else if (switch)
	
else if (js)

else if (query)
	
else if (database)
	
else if (debugger)

else
	:<error>;

endif;

:<void>;

stop

@enduml