@startuml

!include uml_style.iuml
title RichBlock.step()

start

if (value1.isNull()) then (Да)
	:прерывание для выполнения
	первой часть;
	note left
		При завершениях будет
		выполняться первая
		анонимная функция
	end note
	:return false;
	end
else

endif

if (value2.isNull()) then (Да)
	:прерывание для выполннения
	второй часть;
	note left
		При завершениях будет
		выполняться вторая
		анонимная функция
	end note
	:return false;
	end
endif

:result = calcResult();
:resultCalculed = true;
:return true;
stop


@enduml