!include uml_style.iuml
title Call.checkPrev(prev)
skinparam defaultTextAlignment left

start

:return prev == nullptr
|| prev.role == If
|| prev.role == Else
|| prev.role == Assign
|| prev.isResultative();

stop
@enduml