@startuml

!include uml_style.iuml

start
:save;

:to;
if ()
	if (local.)
	else if (l.)
	else if (state.)
	else if (s.)
	else if (@.)
	else if (@.@..@.)
	else if (@3.)
	else if (@name.)
	endif
	:varname;
else
	:@;
endif

stop

@enduml