@startuml

!include wb_style.iuml

start
:js;

if (run)
	if ()
		:file;
		if ()
			:async;
		endif;
		:file name;
		if ()
			::;
			:return type;
			:{;
			:<type>;
			:};
		else
			:{};
		endif
	else
		if ()
			:async;
		endif;
		:{;
		:JS code;
		:};
		if ()
			::;
			:return type;
			:{;
			:<type>;
			:};
		endif;
	endif;

else if (set)
	:JS var name;
	::;
	if ()
		:variable name;
	else
		:constant value;
	endif;

else if (get)
	:JS var name;
	::;
	:var type;
	:{;
	:<type>;
	:};

endif

stop

@enduml