@startuml

!include uml_style.iuml

title LogicBlock* from_expression (QString str, int begin, int end)

start

:i = begin;

while (i < end; i++)

	:operator founded = false;

	if (!) then (yes)
		:begin = i;
		if (str[i+1] == "!")
			:end = i+2;
			:i++;
		else
			:end = i+1;
		endif;
		:continue;
	
	else if (( || [)
		:fly to the bracket pair;
		:find operator|
	
	else if (digit)
		:fly to number end;
		:find operator|
	
	else if (letter)
		:fly to endintifier end;
		:find operator|
		
	else if (")
		:fly to string end;
		:find operator|
		
	endif

	if (rich operator found) 
		:break;
	endif
	
endwhile

:logic_exp_2|

stop

@enduml