@startuml

!include uml_style.iuml

start
:<web>elements;

if (filter)
	:by;
	if ()
		:content;
	else
		:string css selector;
	endif
	
	if ()
		:one;
	endif
	
	:{;
	:<web>element[s];
	:};
	
else if (get)
	:number;
	:{;
	:<web>element;
	:};
	
else if (length)
	:{;
	:<int>;
	:};
	
else
	:error;

endif

stop

@enduml