@startuml

!include uml_style.iuml

start
:<web>element;

if (visible) 
	:{;
	:<bool>;
	:};

else if (x)
	:{;
	:<int>;
	:};

else if (y)
	:{;
	:<int>;
	:};

else if (click)
	if ()
		:goto;
	endif;

else if (send)
	:key;
	:int key code;
	:string modifiers;
	:string text;
	if ()
		:goto;
	endif;

'else if (cast)
'	:to;
'	:<a>element;
'	:switch current context type;

else
	:error;

endif


stop

@enduml