from pygments.lexer import RegexLexer, bygroups
from pygments.token import *

import re

__all__=['IclLexer']

class IclLexer(RegexLexer):
    name = 'Icl'
    aliases = ['icL']
    filenames = ['*.icL', '*.icL-Pro']
    flags = re.MULTILINE | re.UNICODE

    tokens = {
        'root' : [
            (u'\\b(now|if|else|for|filter|range|exists|while|do|any|emit|emiter|slot|assert|listen|wait|jammer|switch|case)\\b', bygroups(Keyword)),
            (u'\\b(bool|int|double|string|list|element|set|item|object|void|regex|datetime|session|window|cookie|tab|document|file|query|database|dbmanager|js-file|code-(icl|js|sql)|handler|any|type)\\b', bygroups(Keyword.Type)),
            (u'\\b(icL|Log|Tab|Document|Import|true|false|Numbers|Types|Key|Alert|By|DSV|Sessions?|Windows?|Cookies|Tabs?|Files?|Make|Math|Wait|Mouse|Move|Stacks?|State|DB|Query|DBManager|Code|Signal|Datetime)\\b', bygroups(Name.Class)),
            (u'(\\\'[\\w\\-\\*]+)', bygroups(Name)),
            (u'(sql)({)', bygroups(Name.Function, Punctuation), 'main__1'),
            (u'(icl)(:pro)?({)', bygroups(Name.Function, Keyword.Pseudo, Punctuation)),
            (u'(\\.\\w+)', bygroups(Name.Function)),
            (u'\\b(emit|slot)(:\\w+)\\b', bygroups(Keyword, Keyword.Pseudo)),
            (u'\\b(css)(:all|:try|:try\\d+m?s|:wait\\d+m?s)?(@\\w*)?(\\[)', bygroups(Name.Function, Keyword.Pseudo, Name.Variable, Punctuation), 'main__2'),
            (u'\\b(xpath)(:all|:try|:try\\d+m?s|:wait\\d+m?s)?(@\\w*)?(\\[)(.*?)(\\])', bygroups(Name.Function, Keyword.Pseudo, Name.Variable, Punctuation, String, Punctuation)),
            (u'\\b(link)(:fragment|:try|:try\\d+m?s|:wait\\d+m?s)?(@\\w*)?(\\[)(.*?)(\\])', bygroups(Name.Function, Keyword.Pseudo, Name.Variable, Punctuation, String, Punctuation)),
            (u'\\b(links)(:fragment)?(@\\w*)?(\\[)(.*?)(\\])', bygroups(Name.Function, Keyword.Pseudo, Name.Variable, Punctuation, String, Punctuation)),
            (u'\\b(tag|button|input|field|h[1-6]|legend|span)(:try|:try\\d+m?s|:wait\\d+m?s)?(@\\w*)?(\\[)(.*?)(\\])', bygroups(Name.Function, Keyword.Pseudo, Name.Variable, Punctuation, String, Punctuation)),
            (u'\\b(tags)(@\\w*)?(\\[)(.*?)(\\])', bygroups(Name.Function, Name.Variable, Punctuation, String, Punctuation)),
            (u'\\b(web)(\\[\\])', bygroups(Name.Function, Punctuation)),
            (u'\\b(js)(:value)?(@\\w+)?({)', bygroups(Name.Function, Keyword.Pseudo, Name.Variable, Punctuation), 'main__3'),
            (u'\\b(js)(:file)(\\[)(.*?)(\\])', bygroups(Name.Function, Keyword.Pseudo, Punctuation, String, Punctuation)),
            (u'(\\$\\w+)', bygroups(Name.Function)),
            (u'(@\\w+)', bygroups(Name.Variable)),
            (u'(#\\w+)', bygroups(Name.Variable.Global)),
            (u'(#)', bygroups(Name.Variable)),
            (u'(:)(not|alive|ignore|ajax|\\d+m?s|alt|ever|\\d+times|reverse|max\\d+|min\\d+|all|fragment|try\\d+m?s|try|wait\\d+m?s)\\b', bygroups(Keyword.Pseudo, Keyword.Pseudo)),
            (u'\\b(\\d+\\.?\\d*?)\\b', bygroups(Number)),
            (u'(//.*?//|/:.*?:/|/\\$.*?\\$/|/\".*?\"/)(\\w*)', bygroups(String.Regex, String.Regex)),
            (u'\\b(sessions|windows|tabs|cookies|alert|tabs|css|xpath|links?|tags?|button|input|field|web|h[1-6]|legend|span)\\b', bygroups(Generic.Error)),
            (u'(\\\")', bygroups(String), 'main__4'),
            (u'(```)', bygroups(Comment), 'main__5'),
            (u'(``)', bygroups(Comment), 'main__6'),
            (u'(`)', bygroups(Comment), 'main__7'),
            (u'(:\\[)', bygroups(Punctuation), 'main__8'),
            (u'(\\[)', bygroups(Punctuation), 'main__9'),
            (u'(;)', bygroups(Punctuation)),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'jsCode__1' : [
            (u'\\b(abstract|arguments|await|boolean|break|byte|case|catch|char|class|const|continue|debugger|default|delete|do|double|else|enum|eval|export|extends|false|final|finally|float|for|function|goto|if|implements|import|in|instanceof|int|interface|let|long|native|new|null|package|private|protected|public|return|short|static|super|switch|synchronized|this|throw|throws|transient|true|try|typeof|var|void|volatile|while|with|yield)\\b', bygroups(Keyword)),
            (u'(\\${[\\w\\_]+})', bygroups(Name.Function)),
            (u'(\\.[\\w\\_]+)(\\s*\\()', bygroups(Name.Function, Punctuation)),
            (u'(\\.[\\w\\_]+)', bygroups(Name)),
            (u'\\b(window|document|crossfire)\\b', bygroups(Name.Class)),
            (u'({)', bygroups(Punctuation), 'jsCode__1'),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__1' : [
            (u'\\b(SELECT|FROM|WHERE|LIMIT|INSERT|INTO|VALUE)\\b', bygroups(Keyword)),
            (u'(@?:[\\w\\_]+)', bygroups(Name.Variable)),
            (u'(#:[\\w\\_]+)', bygroups(Name.Variable.Global)),
            (u'([\\w\\_]+)(\\s*\\()', bygroups(Name.Function, Punctuation)),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__2' : [
            (u'(\\.[\\w\\-\\_]+)', bygroups(Name.Class)),
            (u'(\\#[\\w\\-\\_]+)', bygroups(Name.Variable.Instance)),
            (u'(\\:[\\w\\-\\_]+)(\\s*\\()', bygroups(Name.Function, Punctuation)),
            (u'(\\:[\\w\\-\\_]+)', bygroups(Name)),
            (u'\\b([\\w\\-\\_]+)(=[^\\w\\n\\r]?)([\\w\\-\\_]+)', bygroups(Name, Punctuation, String)),
            (u'\\b(\\d+)\\b', bygroups(Number)),
            (u'\\b([\\w\\-\\_]+)\\b', bygroups(Keyword.Type)),
            (u'(\\[)', bygroups(Punctuation), 'webElement__1'),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__3' : [
            (u'\\b(abstract|arguments|await|boolean|break|byte|case|catch|char|class|const|continue|debugger|default|delete|do|double|else|enum|eval|export|extends|false|final|finally|float|for|function|goto|if|implements|import|in|instanceof|int|interface|let|long|native|new|null|package|private|protected|public|return|short|static|super|switch|synchronized|this|throw|throws|transient|true|try|typeof|var|void|volatile|while|with|yield)\\b', bygroups(Keyword)),
            (u'(\\${[\\w\\_]+})', bygroups(Name.Function)),
            (u'(\\.[\\w\\_]+)(\\s*\\()', bygroups(Name.Function, Punctuation)),
            (u'(\\.[\\w\\_]+)', bygroups(Name)),
            (u'\\b(window|document|crossfire)\\b', bygroups(Name.Class)),
            (u'({)', bygroups(Punctuation), 'jsCode__1'),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__4' : [
            (u'(\\\\.)', bygroups(String)),
            (u'(.)', bygroups(String)),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__5' : [
            ('(\n|\r|\r\n)', String),
            ('.', Comment),
        ], 
        'main__6' : [
            ('(\n|\r|\r\n)', String),
            ('.', Comment),
        ], 
        'main__7' : [
            ('(\n|\r|\r\n)', String),
            ('.', Comment),
        ], 
        'main__8' : [
            (u'\\b(not|alive|ignore|ajax|\\d+m?s|alt|ever|\\d+times|reverse|max\\d+|min\\d+|all|fragment|try\\d+m?s|try|wait\\d+m?s)\\b', bygroups(Keyword.Pseudo)),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'main__9' : [
            (u'\\b(now|if|else|for|filter|range|exists|while|do|any|emit|emiter|slot|assert|listen|wait|jammer|switch|case)\\b', bygroups(Keyword)),
            (u'\\b(bool|int|double|string|list|element|set|item|object|void|regex|datetime|session|window|cookie|tab|document|file|query|database|dbmanager|js-file|code-(icl|js|sql)|handler|any|type)\\b', bygroups(Keyword.Type)),
            (u'\\b(icL|Log|Tab|Document|Import|true|false|Numbers|Types|Key|Alert|By|DSV|Sessions?|Windows?|Cookies|Tabs?|Files?|Make|Math|Wait|Mouse|Move|Stacks?|State|DB|Query|DBManager|Code|Signal|Datetime)\\b', bygroups(Name.Class)),
            (u'(\\\'[\\w\\-\\*]+)', bygroups(Name)),
            (u'(sql)({)', bygroups(Name.Function, Punctuation), 'main__1'),
            (u'(icl)(:pro)?({)', bygroups(Name.Function, Keyword.Pseudo, Punctuation)),
            (u'(\\.\\w+)', bygroups(Name.Function)),
            (u'\\b(emit|slot)(:\\w+)\\b', bygroups(Keyword, Keyword.Pseudo)),
            (u'\\b(css)(:all|:try|:try\\d+m?s|:wait\\d+m?s)?(@\\w*)?(\\[)', bygroups(Name.Function, Keyword.Pseudo, Name.Variable, Punctuation), 'main__2'),
            (u'\\b(xpath)(:all|:try|:try\\d+m?s|:wait\\d+m?s)?(@\\w*)?(\\[)(.*?)(\\])', bygroups(Name.Function, Keyword.Pseudo, Name.Variable, Punctuation, String, Punctuation)),
            (u'\\b(link)(:fragment|:try|:try\\d+m?s|:wait\\d+m?s)?(@\\w*)?(\\[)(.*?)(\\])', bygroups(Name.Function, Keyword.Pseudo, Name.Variable, Punctuation, String, Punctuation)),
            (u'\\b(links)(:fragment)?(@\\w*)?(\\[)(.*?)(\\])', bygroups(Name.Function, Keyword.Pseudo, Name.Variable, Punctuation, String, Punctuation)),
            (u'\\b(tag|button|input|field|h[1-6]|legend|span)(:try|:try\\d+m?s|:wait\\d+m?s)?(@\\w*)?(\\[)(.*?)(\\])', bygroups(Name.Function, Keyword.Pseudo, Name.Variable, Punctuation, String, Punctuation)),
            (u'\\b(tags)(@\\w*)?(\\[)(.*?)(\\])', bygroups(Name.Function, Name.Variable, Punctuation, String, Punctuation)),
            (u'\\b(web)(\\[\\])', bygroups(Name.Function, Punctuation)),
            (u'\\b(js)(:value)?(@\\w+)?({)', bygroups(Name.Function, Keyword.Pseudo, Name.Variable, Punctuation), 'main__3'),
            (u'\\b(js)(:file)(\\[)(.*?)(\\])', bygroups(Name.Function, Keyword.Pseudo, Punctuation, String, Punctuation)),
            (u'(\\$\\w+)', bygroups(Name.Function)),
            (u'(@\\w+)', bygroups(Name.Variable)),
            (u'(#\\w+)', bygroups(Name.Variable.Global)),
            (u'(#)', bygroups(Name.Variable)),
            (u'(:)(not|alive|ignore|ajax|\\d+m?s|alt|ever|\\d+times|reverse|max\\d+|min\\d+|all|fragment|try\\d+m?s|try|wait\\d+m?s)\\b', bygroups(Keyword.Pseudo, Keyword.Pseudo)),
            (u'\\b(\\d+\\.?\\d*?)\\b', bygroups(Number)),
            (u'(//.*?//|/:.*?:/|/\\$.*?\\$/|/\".*?\"/)(\\w*)', bygroups(String.Regex, String.Regex)),
            (u'\\b(sessions|windows|tabs|cookies|alert|tabs|css|xpath|links?|tags?|button|input|field|web|h[1-6]|legend|span)\\b', bygroups(Generic.Error)),
            (u'(\\\")', bygroups(String), 'main__4'),
            (u'(```)', bygroups(Comment), 'main__5'),
            (u'(``)', bygroups(Comment), 'main__6'),
            (u'(`)', bygroups(Comment), 'main__7'),
            (u'(:\\[)', bygroups(Punctuation), 'main__8'),
            (u'(\\[)', bygroups(Punctuation), 'main__9'),
            (u'(;)', bygroups(Punctuation)),
            (u'(\\w+)', bygroups(Name)),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ], 
        'webElement__1' : [
            (u'(\\.[\\w\\-\\_]+)', bygroups(Name.Class)),
            (u'(\\#[\\w\\-\\_]+)', bygroups(Name.Variable.Instance)),
            (u'(\\:[\\w\\-\\_]+)(\\s*\\()', bygroups(Name.Function, Punctuation)),
            (u'(\\:[\\w\\-\\_]+)', bygroups(Name)),
            (u'\\b([\\w\\-\\_]+)(=[^\\w\\n\\r]?)([\\w\\-\\_]+)', bygroups(Name, Punctuation, String)),
            (u'\\b(\\d+)\\b', bygroups(Number)),
            (u'\\b([\\w\\-\\_]+)\\b', bygroups(Keyword.Type)),
            (u'(\\[)', bygroups(Punctuation), 'webElement__1'),
            ('(\n|\r|\r\n)', String),
            ('.', String),
        ]
    }

