<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>icL</string>
    <string>icL-Pro</string>
   </array>
  <key>name</key>
  <string>icL</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.icL</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b(now|if|else|for|filter|range|exists|while|do|any|emit|emiter|slot|assert|listen|wait|jammer|switch|case)\b</string>
          <key>name</key>
          <string>keyword.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(bool|int|double|string|list|element|set|item|object|void|regex|datetime|session|window|cookie|tab|document|file|query|database|dbmanager|js-file|code-(icl|js|sql)|handler|any|type)\b</string>
          <key>name</key>
          <string>meta.type.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(icL|Log|Tab|Document|Import|true|false|Numbers|Types|Key|Alert|By|DSV|Sessions?|Windows?|Cookies|Tabs?|Files?|Make|Math|Wait|Mouse|Move|Stacks?|State|DB|Query|DBManager|Code|Signal|Datetime)\b</string>
          <key>name</key>
          <string>meta.class.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\&apos;[\w\-\*]+)</string>
          <key>name</key>
          <string>variable.other.member.icL</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(sql)({)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(icl)(:pro)?({)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.icL</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.\w+)</string>
          <key>name</key>
          <string>entity.name.function.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(emit|slot)(:\w+)\b</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b(css)(:all|:try|:try\d+m?s|:wait\d+m?s)?(@\w*)?(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.icL</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.icL</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(xpath)(:all|:try|:try\d+m?s|:wait\d+m?s)?(@\w*)?(\[)(.*?)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.icL</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.icL</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>string.quoted.single.icL</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(link)(:fragment|:try|:try\d+m?s|:wait\d+m?s)?(@\w*)?(\[)(.*?)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.icL</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.icL</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>string.quoted.single.icL</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(links)(:fragment)?(@\w*)?(\[)(.*?)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.icL</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.icL</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>string.quoted.single.icL</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(tag|button|input|field|h[1-6]|legend|span)(:try|:try\d+m?s|:wait\d+m?s)?(@\w*)?(\[)(.*?)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.icL</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.icL</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>string.quoted.single.icL</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(tags)(@\w*)?(\[)(.*?)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.other.icL</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>string.quoted.single.icL</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(web)(\[\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>\b(js)(:value)?(@\w+)?({)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.icL</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.icL</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(js)(:file)(\[)(.*?)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.icL</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>string.quoted.single.icL</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$\w+)</string>
          <key>name</key>
          <string>entity.name.function.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(@\w+)</string>
          <key>name</key>
          <string>variable.other.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(#\w+)</string>
          <key>name</key>
          <string>variable.language.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(#)</string>
          <key>name</key>
          <string>variable.other.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(:)(not|alive|ignore|ajax|\d+m?s|alt|ever|\d+times|reverse|max\d+|min\d+|all|fragment|try\d+m?s|try|wait\d+m?s)\b</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.tag.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(\d+\.?\d*?)\b</string>
          <key>name</key>
          <string>constant.numeric.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*?//|/:.*?:/|/\$.*?\$/|/&quot;.*?&quot;/)(\w*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>string.regexp.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(sessions|windows|tabs|cookies|alert|tabs|css|xpath|links?|tags?|button|input|field|web|h[1-6]|legend|span)\b</string>
          <key>name</key>
          <string>invalid.icL</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.quoted.single.icL</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.quoted.single.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(```)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.icL</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.icL</string>
          <key>end</key>
          <string>(```)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(``)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.icL</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.icL</string>
          <key>end</key>
          <string>($)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(`)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.icL</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.icL</string>
          <key>end</key>
          <string>(`)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(:\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__8</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__9</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.icL</string>
        </dict>
       </array>
    </dict>
    <key>jsCode</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b(abstract|arguments|await|boolean|break|byte|case|catch|char|class|const|continue|debugger|default|delete|do|double|else|enum|eval|export|extends|false|final|finally|float|for|function|goto|if|implements|import|in|instanceof|int|interface|let|long|native|new|null|package|private|protected|public|return|short|static|super|switch|synchronized|this|throw|throws|transient|true|try|typeof|var|void|volatile|while|with|yield)\b</string>
          <key>name</key>
          <string>keyword.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\${[\w\_]+})</string>
          <key>name</key>
          <string>entity.name.function.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.[\w\_]+)(\s*\()</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.[\w\_]+)</string>
          <key>name</key>
          <string>variable.other.member.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(window|document|crossfire)\b</string>
          <key>name</key>
          <string>meta.class.icL</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>({)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#jsCode__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>jsCode__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#jsCode</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#sqlCode</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#webElement</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#jsCode</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__6</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__7</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__8</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b(not|alive|ignore|ajax|\d+m?s|alt|ever|\d+times|reverse|max\d+|min\d+|all|fragment|try\d+m?s|try|wait\d+m?s)\b</string>
          <key>name</key>
          <string>entity.name.tag.icL</string>
        </dict>
       </array>
    </dict>
    <key>main__9</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>variable.other.member.icL</string>
        </dict>
       </array>
    </dict>
    <key>sqlCode</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b(SELECT|FROM|WHERE|LIMIT|INSERT|INTO|VALUE)\b</string>
          <key>name</key>
          <string>keyword.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(@?:[\w\_]+)</string>
          <key>name</key>
          <string>variable.other.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(#:[\w\_]+)</string>
          <key>name</key>
          <string>variable.language.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\w\_]+)(\s*\()</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>string</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\\.)</string>
          <key>name</key>
          <string>string.quoted.single.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.)</string>
          <key>name</key>
          <string>string.quoted.single.icL</string>
        </dict>
       </array>
    </dict>
    <key>webElement</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\.[\w\-\_]+)</string>
          <key>name</key>
          <string>meta.class.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\#[\w\-\_]+)</string>
          <key>name</key>
          <string>entity.name.struct.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\:[\w\-\_]+)(\s*\()</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\:[\w\-\_]+)</string>
          <key>name</key>
          <string>entity.name.enum.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([\w\-\_]+)(=[^\w]?)([\w\-\_]+)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.other.member.icL</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.quoted.single.icL</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(\d+)\b</string>
          <key>name</key>
          <string>constant.numeric.icL</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([\w\-\_]+)\b</string>
          <key>name</key>
          <string>entity.name.type.icL</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#webElement__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.icL</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>webElement__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#webElement</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
