@startuml

!include uml_style.iuml
title Поиск конца блока интрукций
start

:обнуление счётчика фигуных скобок (далее СФС);

while (не конец файла и не конец блока инструкций?)
	-[#blue]-> Да;
	:символ для поиска (далее СДП) = '\0';
	:получения следующего символа|
	if (это '?) then (Да)
		-[#blue]->
		:СДП = ';
	else if (это "?) then (Да)
		-[#blue]->
		:СДП = ";
	else if (это {?) then (Да)
		-[#blue]->
		:СФС++;
	else if (это }?) then (Да)
		-[#blue]->
		if (СФС > 0?) then (Да)
			:СФС--;
		else (Нет)
			:break;
		endif
	else (Нет)
		-[#red]->
	endif
	-[#orange]->
endwhile (Нет)

if (СДП != '\0') then (Да)
	-[#blue]->
	while (не конец файла и текущий символ != СДП?)
		-[#blue]-> Да;
		:Получить следующий символ;
		if (текущий символ == \) then (Да)
			-[#blue]->
			:получить следующий символ;
		else (Нет)
			-[#red]->
		endif
		-[#orange]->
	endwhile (Нет)
else (Нет)
	-[#red]->
endif

stop
@enduml