@startuml

!include uml_style.iuml
title Парсинг ключевых слов

start

if (это if?) then (Да)
	-[#blue]->
	:получить
	грани
	логического
	выражения|
	:получить
	грани
	выполняемого
	кода|
	:создать
	контекст;
else if (это else?) then (Да)
	-[#blue]->
	:получить следующее слова;
	if (это if?) then (Да)
		-[#blue]->
		:создать
		контекст
		без
		кода;
	else (Нет)
		-[#red]->
		:получить
		грани
		выполняемого
		кода|
		:создать
		контекст;
	endif
else if (это catch?) then (Да)
	-[#blue]->
	:получить
	код ошибки|
	:получить
	грани
	выполняемого
	кода|
else if (это true?) then (Да)
	-[#blue]->
	:создать
	контекст
	со значением
	true;
else if (это false?) then (Да)
	-[#blue]->
	:создать
	контекст
	со значением
	false;
else (Нет)
	-[#red]->
	:создать
	контекст
	типа
	string;
endif

stop

@enduml