@startuml

!include uml_style.iuml
title Парсинг специальных констукций
start

:ch =  следующий символ;
if (ch <= 42) then (Да)
	-[#blue]->
	if (ch == ") then (Да)
		-[#blue]->
		:парсинг\nстроки|
	else if (ch == #) then (Да)
		-[#blue]->
		:парсинг\nперемен\nсостояния|
	else if (ch == $) then (Да)
		-[#blue]->
		:парсинг\nвыражений\njavascript|
	else if (ch == ') then (Да)
		-[#blue]->
		:парсинг\nизолируемого\nконтекста|
	else if (ch == () then (Да)
		-[#blue]->
		:парсинг\nконтекста\nзахвата\nисключения|
	else if (ch == *) then (Да)
		-[#blue]->
		:парсинг\nфункций|
	else (Нет)
		-[#red]->
		:ошибка:\nнеожиданый\nсимвол>
	endif
else (Нет)
	-[#red]->
endif

if (ch > 42 && ch < 65) then (Да)
	-[#blue]->
	if (ch.isDigit() || ch == -) then (Да)
		-[#blue]->
		:парсинг чисел|
	else if (ch == .) then (Да)
		-[#blue]->
		:парсинг\nсвойств|
	else if (ch == :) then (Да)
		-[#blue]->
		:парсинг\nметодов|
	else if (ch == <) then (Да)
		-[#blue]->
		:парсинг\nаргументов|
	else if (ch == =) then (Да)
		-[#blue]->
		:создание\nблока с\nролем\nAssign;
	else if (ch == >) then (Да)
		-[#blue]->
		:парсинг\nпробразований|
	else (Нет)
		-[#red]->
		:ошибка:\nнеожиданый\nсимвол>
	endif
else (Нет)
	-[#red]->
endif

if (ch >= 65) then (Да)
	-[#blue]->
	if (ch == @) then (Да)
		-[#blue]->
		:парсинг\nлокальной\nперемены|
	else if (ch == [) then (Да)
		-[#blue]->
		:парсинг\nсписка|
	else if (ch == _) then (Да)
		-[#blue]->
		:парсинг\nсистемной\nперемены|
	else if (ch == {) then (Да)
		-[#blue]->
		:парсинг\nблока\nконструкций|
	else if (ch == |) then (Да)
		-[#blue]->
		:парсинг\nблока\nзамены|
	else if (ch == ~) then (Да)
		-[#blue]->
		:парсинг\nвызова\nисклющений|
	else (Нет)
		-[#red]->
		:ошибка:\nнеожиданый\nсимвол>
	endif
else (Нет)
	-[#red]->
endif

stop
@enduml