@startuml

!include uml_style.iuml
title Пропуск коментария

start

:получение следующего символа|

if (это `?) then (Да)
	-[#blue]->
	:получение следующего символа|
	if (это `?) then (Да)
		-[#blue]->
		while (конец коментария не найден?)
			-[#blue]-> Да;
			:поиск следующего `|
			:получения сдедующих 2 символов;
			if (они оба `?) then (Да)
				-[#blue]->
				:конец коментария найден!;
			endif
			-[#orange]->
		endwhile (Нет)
	else (Нет)
		-[#red]->
		:пропуск кода до \\n;
endif
else (Нет)
	-[#red]->
	:поиск следующего `|
endif


stop

@enduml