@startuml

!include uml_style.iuml
title Поиск грани комманды

start

:получение следующего символа|

if (это {?) then (Да)
	-[#blue]->
	:левая грань = текущая позиция + 1;
	:поиск конца блока команд;
	if (текущий символ }?) then (Да)
		-[#blue]->
		:синтаксическая\nошибка>
	else (Нет)
		-[#red]->
		:правая грань =\nтекущая позиция;
	endif
else (Нет)
	-[#red]->
	:поиск один из символов окончания комманды|
	if (найдено ;?) then (Да)
		-[#blue]->
		:правая грань = текущая позиция;
		:ВиртиальнаяМашина\n.commandProcessing = false;
	else (Нет)
		-[#red]->
		:синтаксичексая ошибка>
	endif
endif

stop

@enduml