@startuml

!include uml_style.iuml
title Парсинг ключевых слов

start

if (это if?) then (Да)
	-[#blue]->
	:получить\nграни\nлогической\nвыражний|
	:получить\nграни\nвыпольняемого\nкода|
	:создать\nконтекст;
else if (это else?) then (Да)
	-[#blue]->
	:получить следующее слова;
	if (это if?) then (Да)
		-[#blue]->
		:создать\nконтекст\nбез\nкода;
	else (Нет)
		-[#red]->
		:получить\nграни\nвыпольняемого\nкода|
		:создать\nконтекст;
	endif
else if (это catch?) then (Да)
	-[#blue]->
	:получить\nкод ошибки|
	:получить\nграни\nвыпольняемого\nкода|
else if (это true?) then (Да)
	-[#blue]->
	:создать\nконтекст\nс\nзначением\ntrue;
else if (это false?) then (Да)
	-[#blue]->
	:создать\nконтекст\nс\nзначением\nfalse;
else (Нет)
	-[#red]->
	:создать\nконтекст\nтипа\nstring;
endif

stop

@enduml