@startuml

!include uml_style.iuml
title Парсинг аргумента
start

:Получения типa данных;
:Получения текущего или следующего символа;

if (Тип зарегистрирован?) then (Да)
	-[#blue]->
	if (текущий символ >?) then (Да)
		-[#blue]->
		:получения имени премены|
		:создание контекста;
	else (Нет)
		-[#red]->
		:синтаксичекая ошибка: неожиднный символ>
	endif
else (Нет)
	-[#red]->
	:синтаксическая ошибка: нейсвестный тип данных>
endif

stop
@enduml