@startuml

!include uml_style.iuml
title Парсинг пробразовании
start

:Получения типa данных;
:Получения индентификатора типа;

if (Тип зарегистрирован?) then (Да)
	:создание контекста;
else (Нет)
	:синтаксическая ошибка: нейсвестный тип данных>
endif

stop
@enduml