@startuml

!include uml_style.iuml
title Парсинг преобразований
start

:Получения типа данных;
:Получения идентификатора типа;

if (Тип зарегистрирован?) then (Да)
	-[#blue]->
	:создание контекста;
else (Нет)
	-[#red]->
	:синтаксическая ошибка: неизвестный тип данных>
endif

stop
@enduml