@startuml

!include uml_style.iuml
skinparam defaultTextAlignment left

title Подготовка для $set и $''
start

:code = код javascript;
:replace(code, "#{(\w+)}", [](QString &name, QString&){\n\treturn vm.globalValue(name).toString();\n})|
:replace(code, "@{(\w*)}", [](QString &name, QString&){\n\treturn vm.localValue(name).toString();\n})|

stop
@enduml