@startuml

!include uml_style.iuml
title Парсинг перемен стека
start

:получения следующего символа|
if (это буква?) then (Да)
	-[#blue]->
	:получение имени|
	:создание контекста;
else if (это '?) then (Да)
	-[#blue]->
	:поиск парной скобке|
	:создание контекста;
else (Нет)
	-[#red]->
	:создание контекста на
	основе перемены stack;
endif

stop
@enduml