skinparam activityArrowColor black
skinparam activityBorderColor green
skinparam ActivityDiamondBackgroundColor white
skinparam ActivityDiamondBorderColor orange
skinparam actorBorderColor black
skinparam usecaseArrowColor black
skinparam usecaseBorderColor black
skinparam classArrowColor black
skinparam classBorderColor green
skinparam objectBorderColor black
skinparam packageBorderColor black
skinparam componentArrowColor black
skinparam componentBorderColor black
skinparam componentInterfaceBorderColor black
skinparam noteBorderColor black
skinparam stateBorderColor black
skinparam stateArrowColor black
skinparam sequenceArrowColor black
skinparam sequenceLifeLineBorderColor black
skinparam sequenceParticipantBorderColor black
skinparam sequenceBoxLineColor black
skinparam activityBackgroundColor white
skinparam actorBackgroundColor white
skinparam usecaseBackgroundColor white
skinparam classBackgroundColor white
skinparam objectBackgroundColor white
skinparam packageBackgroundColor white
skinparam componentBackgroundColor white
skinparam componentInterfaceBackgroundColor white
skinparam stateBackgroundColor white
skinparam sequenceParticipantBackgroundColor white
skinparam componentstyle uml2
skinparam interface {
  backgroundColor white
  borderColor green
}

skinparam shadowing false
skinparam defaultTextAlignment center
